let destItens = [
  {
    name: 'Tequilla Jose Cuervo',
    desc: '',
    price: 'R$: 18,00',
    img: '',
  },
  {
    name: 'Black Label',
    desc: 'Dose',
    price: 'R$: 23,00',
    img: '',
  },
  {
    name: 'Old Parr',
    desc: 'Dose',
    price: 'R$: 18,00',
    img: '',
  },
  {
    name: 'Old Parr Litro',
    desc: '',
    price: 'R$: 300,00',
    img: '',
  },
  {
    name: 'Chivas',
    desc: 'Dose',
    price: 'R$: 18,00',
    img: '',
  },
  {
    name: 'Red Label',
    desc: 'Dose',
    price: 'R$: 12,00',
    img: '',
  },
  {
    name: 'White Horse',
    desc: '8 anos',
    price: 'R$: 10,00',
    img: '',
  },
  {
    name: 'Jack Daniels',
    desc: 'Dose',
    price: 'R$: 16,80',
    img: '',
  },
  {
    name: 'Teachers',
    desc: 'Dose',
    price: 'R$: 7,00',
    img: '',
  },
  {
    name: 'Smirnoff',
    desc: 'Dose',
    price: 'R$: 7,50',
    img: '',
  },
  {
    name: 'Natasha',
    desc: 'Dose',
    price: 'R$: 4,90',
    img: '',
  },
  {
    name: 'Absolut',
    desc: 'Dose',
    price: 'R$: 14,90',
    img: '',
  },
  {
    name: 'Campari',
    desc: 'Dose',
    price: 'R$: 8,90',
    img: '',
  },
  {
    name: 'Martine',
    desc: 'Dose',
    price: 'R$: 7,90',
    img: '',
  },
  {
    name: 'Montilla',
    desc: 'Dose',
    price: 'R$: 4,90',
    img: '',
  },
  {
    name: 'Bacardi',
    desc: 'Dose',
    price: 'R$: 6,90',
    img: '',
  },
  {
    name: 'Domecq',
    desc: 'Dose',
    price: 'R$: 7,90',
    img: '',
  },
  {
    name: 'Domus',
    desc: 'Dose',
    price: 'R$: 4,90',
    img: '',
  },
  {
    name: 'Dreher',
    desc: 'Dose',
    price: 'R$: 4,90',
    img: '',
  },
  {
    name: 'Alcatrão',
    desc: 'Com mel e limão',
    price: 'R$: 7,90',
    img: '',
  },
  {
    name: 'Creme de menta',
    desc: 'Dose',
    price: 'R$: 9,90',
    img: '',
  },
  {
    name: 'Licor 43',
    desc: 'Dose',
    price: 'R$: 19,90',
    img: '',
  },
  {
    name: 'Gin Tanqueray',
    desc: '',
    price: 'R$: 189,00',
    img: '',
  },
  
  ]